name: Hello
on: 
  push:
  workflow_dispatch:

jobs:
    Deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy code
          run: |
            echo "Deploying code"
            echo "Deployment Successful"